//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.APIBackend {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Human", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API.APIBackend")]
    [System.SerializableAttribute()]
    public partial class Human : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainFault", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API")]
    [System.SerializableAttribute()]
    public partial class DomainFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private API.APIBackend.DomainError CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public API.APIBackend.DomainError Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DomainError", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API")]
    public enum DomainError : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="DomainError")]
        DomainErrorMember = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="APIBackend.APIBackend")]
    public interface APIBackend {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/CreateRangeOfHumans", ReplyAction="http://tempuri.org/APIBackend/CreateRangeOfHumansResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(API.APIBackend.DomainFault), Action="http://tempuri.org/APIBackend/CreateRangeOfHumansDomainFaultFault", Name="DomainFault", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API")]
        void CreateRangeOfHumans(API.APIBackend.Human[] HumanList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/CreateRangeOfHumans", ReplyAction="http://tempuri.org/APIBackend/CreateRangeOfHumansResponse")]
        System.Threading.Tasks.Task CreateRangeOfHumansAsync(API.APIBackend.Human[] HumanList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/CreateHuman", ReplyAction="http://tempuri.org/APIBackend/CreateHumanResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(API.APIBackend.DomainFault), Action="http://tempuri.org/APIBackend/CreateHumanDomainFaultFault", Name="DomainFault", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API")]
        void CreateHuman(API.APIBackend.Human Human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/CreateHuman", ReplyAction="http://tempuri.org/APIBackend/CreateHumanResponse")]
        System.Threading.Tasks.Task CreateHumanAsync(API.APIBackend.Human Human);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/GetHumanById", ReplyAction="http://tempuri.org/APIBackend/GetHumanByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(API.APIBackend.DomainFault), Action="http://tempuri.org/APIBackend/GetHumanByIdDomainFaultFault", Name="DomainFault", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API")]
        API.APIBackend.Human GetHumanById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/GetHumanById", ReplyAction="http://tempuri.org/APIBackend/GetHumanByIdResponse")]
        System.Threading.Tasks.Task<API.APIBackend.Human> GetHumanByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/GetHumans", ReplyAction="http://tempuri.org/APIBackend/GetHumansResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(API.APIBackend.DomainFault), Action="http://tempuri.org/APIBackend/GetHumansDomainFaultFault", Name="DomainFault", Namespace="http://schemas.datacontract.org/2004/07/DomainBellaNS.API")]
        System.Collections.Generic.Dictionary<string, API.APIBackend.Human> GetHumans();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/APIBackend/GetHumans", ReplyAction="http://tempuri.org/APIBackend/GetHumansResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, API.APIBackend.Human>> GetHumansAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APIBackendChannel : API.APIBackend.APIBackend, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIBackendClient : System.ServiceModel.ClientBase<API.APIBackend.APIBackend>, API.APIBackend.APIBackend {
        
        public APIBackendClient() {
        }
        
        public APIBackendClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIBackendClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIBackendClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIBackendClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateRangeOfHumans(API.APIBackend.Human[] HumanList) {
            base.Channel.CreateRangeOfHumans(HumanList);
        }
        
        public System.Threading.Tasks.Task CreateRangeOfHumansAsync(API.APIBackend.Human[] HumanList) {
            return base.Channel.CreateRangeOfHumansAsync(HumanList);
        }
        
        public void CreateHuman(API.APIBackend.Human Human) {
            base.Channel.CreateHuman(Human);
        }
        
        public System.Threading.Tasks.Task CreateHumanAsync(API.APIBackend.Human Human) {
            return base.Channel.CreateHumanAsync(Human);
        }
        
        public API.APIBackend.Human GetHumanById(string id) {
            return base.Channel.GetHumanById(id);
        }
        
        public System.Threading.Tasks.Task<API.APIBackend.Human> GetHumanByIdAsync(string id) {
            return base.Channel.GetHumanByIdAsync(id);
        }
        
        public System.Collections.Generic.Dictionary<string, API.APIBackend.Human> GetHumans() {
            return base.Channel.GetHumans();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, API.APIBackend.Human>> GetHumansAsync() {
            return base.Channel.GetHumansAsync();
        }
    }
}
